print(13 + 15)
print(13.0 + 15.0)
print(13.0 + 25)
print(-(3 * 6.0))
print(3.0 / 2.0)
print(3 / 2)

print("--------------")
print("Floor division")
print("--------------")
print(3 // 2)
print(3.0 // 2)
print(6 // 2)
print(6.0 // 2.0)
print(-9 // 2)
print(1.5 // 0.5)


print("---------------------------------")
print("Modulo operation is defined by")
print("a % b == a - ((a // b) * b)")
print("---------------------------------")
print()
print()
print()
print()
print()
