print(13 + 15)
print(13.0 + 15.0)
print(13.0 + 25)
print(-(3 * 6.0))
print(3.0 / 2.0)
print(3 / 2)

print("--------------")
print("Floor division")
print("--------------")
print(3 // 2)
print(3.0 // 2)
print(6 // 2)
print(6.0 // 2.0)
print(-9 // 2)
print(1.5 // 0.5)


print("---------------------------------")
print("Modulo operation is defined by")
print("a % b == a - ((a // b) * b)")
print("---------------------------------")

print(type(3))
print(type(3.5))
print(type(3.0))
print("-------------------------------------------")
print("This looks random, see details in the code")
print(1 == 1.0)
print(-3 == -3.0)
print(0.2e3 == 200)

print("-------------------------------------------")
print(math.type(3))
print(math.type(3.0))

print("-------------------------------------------")
print(3)
print(3.0)
print(1000)
print(1e3)

print("-------------------------------------------")
print("Hexadecimal constants")
print(0xff)
print(0x1A3)
print(0x0.2)
print(0x1p-1)
print(0xa.bp2)
print("Or going the other way...")
print(string.format("%a", 419))
print(string.format("%a", 0.1))
print("-------------------------------------------")
